### ISSUE TITLE
시험 끝나고 할 것들.

### ISSUE THREAD

**Issue by IAM20** [IAM20/MACloud#14]
을 상의해보자 경모야
@gkrudah 
@gkrudah 
@gkrudah

**Comment by 2013008264** [comment]
시험 끝났으니 방향에 대해서 상의해봅시다.
나중에 소프트웨어 공학때 자유주제로 나올 시, 우리는 어떤 방법론을 통해 이렇게 사용했다! 라고 하기 좋게 
방법론을 정하고 개발하는 것도 나쁘지 않을 듯 함. 

뭐 팀이 너랑 나라서 의미가 있을까 싶긴 한데..

어쨌든 UML 도 미리 그려놓고 하면 좀 도움 될 듯?
@gkrudah
